const { useState, useEffect, useMemo } = React;

/* ============================== API client ============================== */

// Authentication is cookie-based. The server sets an HttpOnly session cookie,
// so JavaScript never reads or stores a credential.
async function api(path, { method = "GET", body } = {}) {
  const res = await fetch("/api" + path, {
    method,
    credentials: "same-origin",
    headers: {
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  let data = {};
  try { data = await res.json(); } catch (e) { /* empty body */ }
  if (!res.ok) {
    const err = new Error(data.error || "Something went wrong. Please try again.");
    err.status = res.status;
    throw err;
  }
  return data;
}

const HOLD_MS = 5 * 60 * 1000;
// This stores only a booking reference, never a credential or payment data.
// The server still checks that the booking belongs to the signed-in user.
const PENDING_BOOKING_KEY = "bdr_pending_booking_pnr";

function fmtDate(iso) {
  return new Date(iso).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });
}
function fmtMMSS(ms) {
  const total = Math.max(0, Math.ceil(ms / 1000));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}
function todayISO() {
  const d = new Date();
  // Do not use toISOString() here: it converts Bangladesh local midnight to
  // the previous UTC day, which made the default search date one day behind
  // the trips generated by PostgreSQL's CURRENT_DATE.
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

/* ============================== Routing ============================== */

// A small, dependency-free router: each "page" the app already tracks in
// state is mapped to a real URL, and browser back/forward is wired through
// popstate. This makes /login, /admin, /mybookings etc. real, bookmarkable,
// shareable addresses instead of purely in-memory state.
const ROUTE_PATHS = {
  home: "/",
  login: "/login",
  results: "/search",
  coach: "/booking/coach",
  seats: "/booking/seats",
  passenger: "/booking/passenger",
  payment: "/booking/payment",
  ticket: "/booking/ticket",
  mybookings: "/mybookings",
  admin: "/admin",
  classinfo: "/classinfo",
  about: "/about",
  contact: "/contact",
  account: "/account",
};
const PAGE_FROM_PATH = Object.fromEntries(Object.entries(ROUTE_PATHS).map(([k, v]) => [v, k]));
function pageFromLocation() {
  return PAGE_FROM_PATH[window.location.pathname] || "home";
}

// Pages that require *some* signed-in user.
const AUTH_ONLY_PAGES = new Set(["mybookings", "admin", "account"]);
// Pages that additionally require the administrator role.
const ADMIN_ONLY_PAGES = new Set(["admin"]);
// Pages that only make sense with in-memory booking context (trip/coach/seat
// selection). These can't be meaningfully deep-linked from a cold URL, so a
// direct visit sends the visitor back to the flow's start instead of
// rendering with missing data.
const CONTEXT_ONLY_PAGES = new Set(["coach", "seats", "passenger", "payment", "ticket"]);

/* ============================== Theme ============================== */

function useTheme() {
  const [theme, setTheme] = useState(localStorage.getItem("bdr_theme") || "light");
  useEffect(() => localStorage.setItem("bdr_theme", theme), [theme]);
  const dark = theme === "dark";
  // A single, restrained accent (emerald) over a neutral gray scale — the
  // same pairing carries through both light and dark mode instead of
  // swapping palettes, which keeps the UI feeling calm and minimal.
  const t = {
    dark,
    pageBg: dark ? "bg-neutral-950" : "bg-neutral-50",
    text: dark ? "text-neutral-100" : "text-neutral-900",
    subtext: dark ? "text-neutral-400" : "text-neutral-500",
    navBg: dark ? "bg-neutral-950/95 border-neutral-800" : "bg-white/95 border-neutral-200",
    cardBg: dark ? "bg-neutral-900 border-neutral-800" : "bg-white border-neutral-200",
    cardAltBg: dark ? "bg-neutral-800/60 border-neutral-700" : "bg-neutral-100 border-neutral-200",
    inputBg: dark ? "bg-neutral-800 border-neutral-700 text-neutral-100" : "bg-white border-neutral-300 text-neutral-900",
    hero: dark ? "bg-neutral-900" : "bg-neutral-900",
    primary: "bg-emerald-600 hover:bg-emerald-500 text-white shadow-sm",
    primaryOutline: dark ? "border border-neutral-700 hover:bg-neutral-800 text-neutral-100" : "border border-neutral-300 hover:border-emerald-400 hover:bg-emerald-50 text-neutral-900",
    divider: dark ? "border-neutral-800" : "border-neutral-200",
  };
  return { theme, setTheme, t };
}

/* ============================== Atoms ============================== */

function Badge({ children, tone = "default", t }) {
  const tones = {
    default: t.dark ? "bg-neutral-800 text-neutral-300" : "bg-neutral-100 text-neutral-600",
    success: "bg-green-100 text-green-700",
    warn: "bg-orange-100 text-orange-700",
    danger: "bg-red-100 text-red-700",
  };
  return <span className={`px-2 py-0.5 rounded text-xs font-medium ${tones[tone]}`}>{children}</span>;
}
function PrimaryButton({ children, onClick, disabled, className = "", t, type = "button" }) {
  return (
    <button type={type} onClick={onClick} disabled={disabled}
      className={`px-5 py-2.5 rounded-xl font-semibold text-sm transition-all disabled:opacity-40 disabled:cursor-not-allowed ${t.primary} ${className}`}>
      {children}
    </button>
  );
}
function OutlineButton({ children, onClick, className = "", t, type = "button" }) {
  return (
    <button type={type} onClick={onClick} className={`px-5 py-2.5 rounded-xl font-semibold text-sm transition-all ${t.primaryOutline} ${className}`}>
      {children}
    </button>
  );
}
function Field({ label, children, t }) {
  return (
    <label className="flex flex-col gap-1.5 text-sm">
      <span className={`font-medium ${t.subtext}`}>{label}</span>
      {children}
    </label>
  );
}
function ErrorBanner({ message }) {
  if (!message) return null;
  return <p role="alert" className="mt-3 text-sm text-red-500 flex items-center gap-1.5">&#9888; {message}</p>;
}
function InfoRow({ t, label, value }) {
  return (
    <div>
      <p className={`text-xs ${t.subtext}`}>{label}</p>
      <p className={`font-medium ${t.text}`}>{value}</p>
    </div>
  );
}
function BackBar({ t, onBack, label, disabled = false }) {
  return (
    <button disabled={disabled} onClick={onBack} className={`mb-4 text-sm flex items-center gap-1.5 disabled:opacity-50 ${t.subtext} hover:text-emerald-600`}>
      &larr; {label}
    </button>
  );
}
function StationSelect({ value, onChange, t, stations, excludeCode, label }) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const ref = React.useRef(null);
  const selected = stations.find((s) => s.station_code === value);
  const options = stations
    .filter((s) => s.station_code !== excludeCode)
    .filter((s) => `${s.station_name} ${s.city} ${s.station_code}`.toLowerCase().includes(query.toLowerCase()));

  useEffect(() => {
    const close = (event) => { if (ref.current && !ref.current.contains(event.target)) setOpen(false); };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, []);

  const choose = (station) => {
    onChange(station.station_code);
    setQuery("");
    setOpen(false);
  };

  return (
    <div className="relative" ref={ref}>
      <button type="button" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((o) => !o)}
        className={`w-full px-3.5 py-3 rounded-xl border text-left flex items-center gap-3 ${t.inputBg} hover:border-emerald-400`}>
        <span className="text-lg">{label === "From" ? "↗" : "↘"}</span>
        <span className="flex-1 min-w-0">
          <span className={`block text-[11px] uppercase tracking-[.16em] ${t.subtext}`}>{label || "Station"}</span>
          <span className={`block truncate text-sm font-semibold ${selected ? t.text : t.subtext}`}>{selected ? `${selected.station_name} · ${selected.city}` : "Choose a station"}</span>
        </span>
        <span className={`text-xs ${t.subtext}`}>⌄</span>
      </button>
      {open && (
        <div role="listbox" className={`station-menu absolute left-0 right-0 z-40 mt-2 rounded-2xl border shadow-2xl overflow-hidden ${t.cardBg}`}>
          <div className={`p-2 border-b ${t.divider}`}>
            <div className={`flex items-center gap-2 px-3 rounded-xl border ${t.cardAltBg}`}>
              <span className={t.subtext}>⌕</span>
              <input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search station or city…"
                className={`w-full bg-transparent py-2.5 text-sm outline-none ${t.text}`} />
            </div>
          </div>
          <div className="station-scroll max-h-64 overflow-y-auto p-1">
            {options.length === 0 && <p className={`px-3 py-4 text-sm ${t.subtext}`}>No matching stations found.</p>}
            {options.map((s) => (
              <button key={s.station_code} type="button" role="option" aria-selected={value === s.station_code} onClick={() => choose(s)}
                className={`w-full px-3 py-2.5 rounded-xl text-left flex items-center justify-between hover:bg-emerald-500/10 ${value === s.station_code ? "bg-emerald-500/10" : ""}`}>
                <span><span className={`block text-sm font-semibold ${t.text}`}>{s.station_name}</span><span className={`block text-xs ${t.subtext}`}>{s.city}</span></span>
                <span className="text-[10px] font-bold tracking-wider text-emerald-600">{s.station_code}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
function JourneySummary({ t, trainName, fromCity, toCity, date, klass, coachNumber, fare }) {
  return (
    <div className={`rounded-xl border p-4 grid grid-cols-2 md:grid-cols-4 gap-3 text-sm ${t.cardAltBg}`}>
      <div><p className={t.subtext}>Train</p><p className={`font-medium ${t.text}`}>{trainName}</p></div>
      <div><p className={t.subtext}>Route</p><p className={`font-medium ${t.text}`}>{fromCity} → {toCity}</p></div>
      <div><p className={t.subtext}>Date</p><p className={`font-medium ${t.text}`}>{fmtDate(date)}</p></div>
      <div><p className={t.subtext}>Class</p><p className={`font-medium ${t.text}`}>{klass}{coachNumber != null ? ` · Coach ${coachNumber}` : ""}</p></div>
      {fare != null && <div><p className={t.subtext}>Fare / seat</p><p className={`font-medium ${t.text}`}>৳{fare}</p></div>}
    </div>
  );
}

/* ============================== Nav ============================== */

function NavBar({ page, go, t, setTheme, currentUser, logout, logoutPending }) {
  const [open, setOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const links = [
    { key: "home", label: "Home" },
    { key: "classinfo", label: "Class Info" },
    { key: "about", label: "About Us" },
    { key: "contact", label: "Contact" },
  ];
  return (
    <header className={`sticky top-0 z-30 border-b ${t.navBg}`}>
      <div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
        <button className="flex items-center gap-2 font-semibold" onClick={() => go("home")}>
          <div className="w-8 h-8 rounded-md bg-neutral-900 dark:bg-emerald-600 flex items-center justify-center text-white text-sm">&#128646;</div>
          <span className={t.text}>BD Railway</span>
        </button>

        <nav className="hidden md:flex items-center gap-6">
          {links.map((l) => (
            <button key={l.key} onClick={() => go(l.key)} className={`text-sm font-medium ${page === l.key ? "text-emerald-600" : t.subtext} hover:text-emerald-600`}>
              {l.label}
            </button>
          ))}
        </nav>

        <div className="hidden md:flex items-center gap-3">
          <button onClick={() => setTheme((th) => (th === "light" ? "dark" : "light"))} className={`p-2 rounded-md ${t.primaryOutline}`}>
            {t.dark ? "\u2600" : "\u263D"}
          </button>
          {currentUser ? (
            <div className="relative">
              <button aria-expanded={menuOpen} onClick={() => setMenuOpen((o) => !o)} className={`flex items-center gap-2 px-3 py-2 rounded-md ${t.primaryOutline}`}>
                <span className="text-sm">{currentUser.first_name}</span>
                <Badge t={t} tone={currentUser.role === "admin" ? "success" : "default"}>{currentUser.role === "admin" ? "Admin" : "Customer"}</Badge>
                <span aria-hidden="true">&#9662;</span>
              </button>
              {menuOpen && (
                <div className={`absolute right-0 mt-2 w-44 rounded-md border shadow-lg py-1 ${t.cardBg}`} onMouseLeave={() => setMenuOpen(false)}>
                  <button onClick={() => { go("mybookings"); setMenuOpen(false); }} className={`w-full text-left px-3 py-2 text-sm hover:bg-emerald-600/10 ${t.text}`}>My Bookings</button>
                  {currentUser.role === "admin" && <button onClick={() => { go("admin"); setMenuOpen(false); }} className={`w-full text-left px-3 py-2 text-sm hover:bg-emerald-600/10 ${t.text}`}>Admin Dashboard</button>}
                  <button onClick={() => { go("account"); setMenuOpen(false); }} className={`w-full text-left px-3 py-2 text-sm hover:bg-emerald-600/10 ${t.text}`}>Profile</button>
                  <button disabled={logoutPending} onClick={() => { logout(); setMenuOpen(false); }} className="w-full text-left px-3 py-2 text-sm text-red-500 hover:bg-red-500/10 disabled:opacity-50">{logoutPending ? "Logging out…" : "Logout"}</button>
                </div>
              )}
            </div>
          ) : (
            <OutlineButton t={t} onClick={() => go("login")}>Login</OutlineButton>
          )}
        </div>

        <button className="md:hidden p-2" onClick={() => setOpen((o) => !o)}>{open ? "\u2715" : "\u2630"}</button>
      </div>

      {open && (
        <div className={`md:hidden border-t ${t.divider} px-4 py-3 flex flex-col gap-3`}>
          {links.map((l) => (
            <button key={l.key} onClick={() => { go(l.key); setOpen(false); }} className={`text-left text-sm font-medium ${t.text}`}>{l.label}</button>
          ))}
          <div className={`h-px border-t ${t.divider}`} />
          {currentUser ? (
            <>
              <p className={`text-xs ${t.subtext}`}>Signed in as <span className="font-medium">{currentUser.role === "admin" ? "Administrator" : "Customer"}</span></p>
              <button onClick={() => { go("mybookings"); setOpen(false); }} className={`text-left text-sm font-medium ${t.text}`}>My Bookings</button>
              {currentUser.role === "admin" && <button onClick={() => { go("admin"); setOpen(false); }} className={`text-left text-sm font-medium ${t.text}`}>Admin Dashboard</button>}
              <button disabled={logoutPending} onClick={() => { logout(); setOpen(false); }} className="text-left text-sm font-medium text-red-500 disabled:opacity-50">{logoutPending ? "Logging out…" : "Logout"}</button>
            </>
          ) : (
            <button onClick={() => { go("login"); setOpen(false); }} className="text-left text-sm font-medium text-emerald-600">Login</button>
          )}
          <button onClick={() => setTheme((th) => (th === "light" ? "dark" : "light"))} className={`self-start px-3 py-1.5 rounded-md text-sm ${t.primaryOutline}`}>
            {t.dark ? "Light mode" : "Dark mode"}
          </button>
        </div>
      )}
    </header>
  );
}

/* ============================== Search card ============================== */

function SearchCard({ t, search, setSearch, onSubmit, error, stations, classTypes }) {
  const swap = () => setSearch((s) => ({ ...s, from: s.to, to: s.from }));
  return (
    <div className={`rounded-xl border shadow-sm p-5 md:p-6 ${t.cardBg}`}>
      <div className="grid grid-cols-1 md:grid-cols-[1fr_auto_1fr] gap-3 items-end">
        <Field label="From" t={t}><StationSelect label="From" value={search.from} onChange={(v) => setSearch((s) => ({ ...s, from: v }))} t={t} stations={stations} excludeCode={search.to} /></Field>
        <button onClick={swap} aria-label="Swap stations" className={`hidden md:flex items-center justify-center w-11 h-11 rounded-full mb-0.5 self-end text-lg ${t.primaryOutline}`}>&#8646;</button>
        <Field label="To" t={t}><StationSelect label="To" value={search.to} onChange={(v) => setSearch((s) => ({ ...s, to: v }))} t={t} stations={stations} excludeCode={search.from} /></Field>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-3">
        <Field label="Journey date" t={t}>
          <input type="date" min={todayISO()} value={search.date} onChange={(e) => setSearch((s) => ({ ...s, date: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} />
        </Field>
        <Field label="Class" t={t}>
          <select value={search.klass} onChange={(e) => setSearch((s) => ({ ...s, klass: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`}>
            <option value="">All Classes</option>
            {classTypes.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
        </Field>
        <div className="flex items-end">
          <PrimaryButton t={t} onClick={onSubmit} className="w-full">&#128269; Search Trains</PrimaryButton>
        </div>
      </div>
      <ErrorBanner message={error} />
    </div>
  );
}

/* ============================== Pages ============================== */

// Common origin/destination pairs, mirroring the "popular routes" shortcuts
// on railway booking sites — a quick way in without typing station names.
const POPULAR_ROUTES = [
  ["DHK", "CTG"],
  ["DHK", "SYL"],
  ["DHK", "RAJ"],
  ["DHK", "KHL"],
];

function StatStrip({ t, stations, classTypes }) {
  const stats = [
    [String(stations.length || "—"), "Stations served"],
    [String(POPULAR_ROUTES.length), "Popular routes"],
    [String(classTypes.length || "—"), "Travel classes"],
    ["24/7", "Online booking"],
  ];
  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-px rounded-xl overflow-hidden border border-white/10 bg-white/10">
      {stats.map(([value, label]) => (
        <div key={label} className="bg-neutral-900 px-4 py-4 text-center">
          <p className="text-2xl font-black text-white">{value}</p>
          <p className="mt-1 text-xs text-neutral-400">{label}</p>
        </div>
      ))}
    </div>
  );
}

function PopularRoutes({ t, stations, onPick }) {
  const cityOf = (code) => stations.find((s) => s.station_code === code)?.city || code;
  if (!stations.length) return null;
  return (
    <section className="max-w-6xl mx-auto px-4 pb-16">
      <div className="mb-6">
        <p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-600">Popular routes</p>
        <h2 className={`mt-2 text-3xl font-black ${t.text}`}>Jump straight to a journey</h2>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {POPULAR_ROUTES.map(([from, to]) => (
          <button key={`${from}-${to}`} onClick={() => onPick(from, to)}
            className={`text-left rounded-2xl border p-5 transition-colors ${t.cardBg} hover:border-emerald-500`}>
            <p className={`text-xs uppercase tracking-wide ${t.subtext}`}>Route</p>
            <p className={`mt-1 font-bold ${t.text}`}>{cityOf(from)} <span className="text-emerald-600">→</span> {cityOf(to)}</p>
            <p className={`mt-3 text-xs font-medium text-emerald-600`}>Search this route &rarr;</p>
          </button>
        ))}
      </div>
    </section>
  );
}

function HomePage({ t, search, setSearch, doSearch, searchError, stations, classTypes }) {
  const steps = [
    ["01", "Pick your route", "Search by station, city, travel date and preferred class."],
    ["02", "Choose your seat", "Compare available coaches and tap the seats you want."],
    ["03", "Add passenger details", "Enter the name and age for every traveller."],
    ["04", "Pay & travel", "Complete the demo payment and keep your digital ticket handy."],
  ];
  const pickRoute = (from, to) => {
    setSearch((s) => ({ ...s, from, to }));
    document.getElementById("search-card")?.scrollIntoView({ behavior: "smooth", block: "start" });
  };
  return (
    <div>
      <section className={`${t.hero} relative overflow-hidden text-white border-b border-neutral-800`}>
        <div className="max-w-6xl mx-auto px-4 pt-14 pb-24 md:pt-20 md:pb-28 relative">
          <div className="max-w-3xl float-in">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold tracking-wide text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400" /> YOUR NEXT JOURNEY STARTS HERE</div>
            <h1 className="mt-6 text-4xl md:text-6xl font-black leading-[1.05] tracking-tight">Go further.<br /><span className="text-emerald-400">Feel closer.</span></h1>
            <p className="mt-5 max-w-xl text-base md:text-lg leading-relaxed text-neutral-300">A smarter, smoother way to discover Bangladesh by rail. Find a train, choose your seat, and book the journey in a few easy steps.</p>
            <div className="mt-7 max-w-xl"><StatStrip t={t} stations={stations} classTypes={classTypes} /></div>
          </div>
        </div>
      </section>
      <div id="search-card" className="max-w-5xl mx-auto px-4 -mt-16 md:-mt-20 relative z-10 scroll-mt-24">
        <SearchCard t={t} search={search} setSearch={setSearch} onSubmit={doSearch} error={searchError} stations={stations} classTypes={classTypes} />
      </div>
      <PopularRoutes t={t} stations={stations} onPick={pickRoute} />
      <section className="max-w-6xl mx-auto px-4 pb-20">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-8">
          <div><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-600">How it works</p><h2 className={`mt-2 text-3xl font-black ${t.text}`}>Your trip, made simple</h2></div>
          <p className={`max-w-sm text-sm leading-relaxed ${t.subtext}`}>From your first search to the final ticket, everything you need is in one clear flow.</p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {steps.map(([number, title, copy], index) => (
            <div key={number} className={`relative rounded-2xl border p-5 ${t.cardBg} ${index === 0 ? "ring-1 ring-emerald-400/30" : ""}`}>
              <div className="flex items-center justify-between"><span className="text-3xl font-black text-emerald-500/25">{number}</span><span className={`h-9 w-9 rounded-xl flex items-center justify-center ${t.cardAltBg} text-emerald-600`}>{["⌕", "▦", "♙", "✓"][index]}</span></div>
              <h3 className={`mt-5 font-bold ${t.text}`}>{title}</h3><p className={`mt-2 text-sm leading-relaxed ${t.subtext}`}>{copy}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

function LoginPage({ t, pendingSearch, onLogin, stations }) {
  const [mode, setMode] = useState("login");
  const [form, setForm] = useState({ first_name: "", last_name: "", email: "", password: "" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const upd = (k, v) => setForm((f) => ({ ...f, [k]: v }));

  const stationCity = (code) => stations.find((s) => s.station_code === code)?.city || code;

  const submit = async (event) => {
    event.preventDefault();
    setError("");
    setLoading(true);
    try {
      const data = mode === "login"
        ? await api("/auth/login", { method: "POST", body: { email: form.email, password: form.password }, auth: false })
        : await api("/auth/register", { method: "POST", body: form, auth: false });
      if (!data.user) throw new Error("The server did not return the signed-in account.");
      // The server sets an HttpOnly session cookie; JavaScript only receives
      // the safe user profile.
      onLogin(data.user);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-md mx-auto px-4 py-14">
      <h1 className={`text-2xl font-bold ${t.text}`}>{mode === "login" ? "Login" : "Create Account"}</h1>

      {pendingSearch && (
        <div className={`mt-4 rounded-md border p-3 text-sm ${t.cardAltBg} ${t.text}`}>
          Please log in to continue with train search and booking.
          <div className={`mt-1 ${t.subtext}`}>
            {stationCity(pendingSearch.from)} → {stationCity(pendingSearch.to)}, {fmtDate(pendingSearch.date)}
            {pendingSearch.klass ? `, ${pendingSearch.klass}` : ""}
          </div>
        </div>
      )}

      <form onSubmit={submit} className={`mt-6 rounded-xl border p-5 space-y-4 ${t.cardBg}`}>
        {mode === "register" && (
          <div className="grid grid-cols-2 gap-3">
            <Field label="First Name" t={t}><input required autoComplete="given-name" value={form.first_name} onChange={(e) => upd("first_name", e.target.value)} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
            <Field label="Last Name" t={t}><input required autoComplete="family-name" value={form.last_name} onChange={(e) => upd("last_name", e.target.value)} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
          </div>
        )}
        <Field label="Email" t={t}><input required type="email" autoComplete="email" value={form.email} onChange={(e) => upd("email", e.target.value)} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
        <Field label="Password" t={t}><input required type="password" minLength={mode === "register" ? 6 : undefined} autoComplete={mode === "login" ? "current-password" : "new-password"} value={form.password} onChange={(e) => upd("password", e.target.value)} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
        {mode === "register" && <p className={`text-xs ${t.subtext}`}>New accounts are created as customers. An existing administrator can grant administrator access later.</p>}
        <ErrorBanner message={error} />
        <PrimaryButton t={t} type="submit" disabled={loading} className="w-full">
          {loading ? "Please wait…" : mode === "login" ? "Login" : "Create Account"}
        </PrimaryButton>
        <div className="flex justify-between text-sm">
          <button type="button" onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }} className="text-emerald-600 hover:underline">
            {mode === "login" ? "Create Account" : "Back to Login"}
          </button>
          {mode === "login" && <button type="button" className="text-emerald-600 hover:underline" onClick={() => setError("Password reset is not available in this demonstration yet. Please contact an administrator.")}>Forgot Password?</button>}
        </div>
        {mode === "login" && (
          <p className={`text-xs ${t.subtext} pt-2 border-t ${t.divider}`}>Customers and administrators use this same sign-in form. Demo customer: <b>rahim@example.com</b> / <b>password123</b>.</p>
        )}
      </form>
    </div>
  );
}

function ResultsPage({ t, search, go, stations }) {
  const [trips, setTrips] = useState(null);
  const [error, setError] = useState("");
  const from = stations.find((s) => s.station_code === search.from);
  const to = stations.find((s) => s.station_code === search.to);
  const clock = (value) => new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  const shortDate = (value) => new Date(value).toLocaleDateString([], { day: "2-digit", month: "short" }).toUpperCase();
  const duration = (start, end) => {
    const mins = Math.max(0, Math.round((new Date(end) - new Date(start)) / 60000));
    return `${String(Math.floor(mins / 60)).padStart(2, "0")}h ${String(mins % 60).padStart(2, "0")}m`;
  };

  useEffect(() => {
    let cancelled = false;
    setTrips(null);
    api(`/search?from=${search.from}&to=${search.to}&date=${search.date}${search.klass ? `&klass=${encodeURIComponent(search.klass)}` : ""}`)
      .then((data) => { if (!cancelled) setTrips(data); })
      .catch((e) => { if (!cancelled) setError(e.message); });
    return () => { cancelled = true; };
  }, [search.from, search.to, search.date, search.klass]);

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6">
        <div>
          <h1 className={`text-xl font-bold ${t.text}`}>{from?.city} → {to?.city}</h1>
          <p className={`text-sm ${t.subtext}`}>{fmtDate(search.date)}{search.klass ? ` · ${search.klass}` : ""}</p>
        </div>
        <OutlineButton t={t} onClick={() => go("home")}>&larr; Modify Search</OutlineButton>
      </div>

      <ErrorBanner message={error} />
      {trips === null && !error && <p className={t.subtext}>Loading trains…</p>}

      {trips && trips.length === 0 && (
        <div className={`rounded-xl border p-8 text-center ${t.cardBg}`}>
          <p className={t.text}>No trains are available for this journey.</p>
        </div>
      )}

      <div className="space-y-4">
        {trips && trips.map((trip) => (
          <div key={trip.trip_id} className={`rounded-xl border p-5 ${t.cardBg}`}>
            <h2 className="font-bold uppercase tracking-wide text-orange-500">{trip.train_name} <span className="font-normal text-slate-500">({trip.train_id})</span></h2>
            <div className="my-4 grid grid-cols-[1fr_auto] items-center border-y -mx-5 px-5 py-3">
              <div className="flex items-center gap-4">
                <div className="w-24 shrink-0 text-right"><p className={`text-xs font-bold ${t.text}`}>{shortDate(trip.origin_departure)} · {clock(trip.origin_departure)}</p><p className={`text-sm ${t.subtext}`}>{from?.city || from?.station_name}</p></div>
                <div className="min-w-12 flex-1 text-center"><div className="relative border-t-2 border-slate-200"><span className="absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 border-2 border-emerald-600 bg-white" /></div><p className={`mt-2 text-xs ${t.subtext}`}>{duration(trip.origin_departure, trip.destination_arrival)}</p></div>
                <div className="w-24 shrink-0"><p className={`text-xs font-bold ${t.text}`}>{shortDate(trip.destination_arrival)} · {clock(trip.destination_arrival)}</p><p className={`text-sm ${t.subtext}`}>{to?.city || to?.station_name}</p></div>
              </div>
              <div className="border-l pl-4 text-center text-emerald-700"><div className="text-xl">⚑</div><span className="text-[11px] font-semibold">Train Details</span></div>
            </div>
            <details className="mb-3 text-xs text-slate-600">
              <summary className="w-fit cursor-pointer font-semibold text-emerald-700">View all station times</summary>
              <div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 rounded-lg bg-slate-50 p-3">
                {(trip.stops || []).map((stop) => <span key={stop.station_code}><b>{stop.city}</b> · Arr {String(stop.arrival_time).slice(0, 5)} / Dep {String(stop.departure_time).slice(0, 5)}</span>)}
              </div>
            </details>
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
              {trip.classes.map((c) => (
                <div key={c.coach_type} className={`flex min-h-36 flex-col justify-between rounded-md border px-3 py-3 ${c.available > 0 ? "border-emerald-700 bg-emerald-50/60" : "border-rose-100 bg-rose-50"}`}>
                  <div>
                    <p className="font-bold text-sm text-slate-700">{c.coach_type.toUpperCase()}</p>
                    <p className="mt-1 text-[11px] leading-tight text-slate-600">Available Tickets<br />(Counter + Online)</p>
                    <p className={`text-sm font-bold ${c.available > 0 ? "text-emerald-700" : "text-red-500"}`}>{c.available}</p>
                  </div>
                  <div className="flex flex-wrap items-center justify-between gap-2 border-t border-black/5 pt-2">
                    <span className={`text-sm font-semibold ${t.text}`}>৳{c.fare}</span>
                    <PrimaryButton t={t} disabled={c.available === 0} onClick={() => go("coach", { tripId: trip.trip_id, klass: c.coach_type, fare: c.fare })}>Book Now</PrimaryButton>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function CoachPage({ t, go, ctx }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api(`/trips/${ctx.tripId}/coaches?klass=${encodeURIComponent(ctx.klass)}`).then(setData).catch((e) => setError(e.message));
  }, [ctx.tripId, ctx.klass]);

  if (error) return <div className="max-w-3xl mx-auto px-4 py-8"><ErrorBanner message={error} /></div>;
  if (!data) return <div className="max-w-3xl mx-auto px-4 py-8"><p className={t.subtext}>Loading…</p></div>;

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <BackBar t={t} onBack={() => go("results")} label="Back to results" />
      <JourneySummary t={t} trainName={data.trip.train_name} fromCity={ctx.search.fromCity} toCity={ctx.search.toCity} date={data.trip.departure_date} klass={ctx.klass} />
      <h2 className={`mt-6 mb-3 font-semibold ${t.text}`}>Select Coach</h2>
      <div className="flex flex-wrap gap-3">
        {data.coaches.map((c) => (
          <button key={c.coach_id} onClick={() => go("seats", { coach: c, trainName: data.trip.train_name, date: data.trip.departure_date })} className={`px-6 py-4 rounded-lg border font-semibold ${t.cardBg} ${t.text} hover:border-emerald-600`}>
            Coach {c.coach_number}
          </button>
        ))}
        {data.coaches.length === 0 && <p className={t.subtext}>No coaches of this class on this train.</p>}
      </div>
    </div>
  );
}

function SeatsPage({ t, go, ctx }) {
  const [seats, setSeats] = useState(null);
  const [error, setError] = useState("");
  const [selected, setSelected] = useState([]);

  useEffect(() => {
    api(`/trips/${ctx.tripId}/coaches/${ctx.coach.coach_id}/seats`).then((d) => setSeats(d.seats)).catch((e) => setError(e.message));
  }, [ctx.tripId, ctx.coach.coach_id]);

  if (error) return <div className="max-w-3xl mx-auto px-4 py-8"><ErrorBanner message={error} /></div>;
  if (!seats) return <div className="max-w-3xl mx-auto px-4 py-8"><p className={t.subtext}>Loading seats…</p></div>;

  const toggle = (seat) => {
    if (seat.taken) return;
    setSelected((sel) => (sel.includes(seat.seat_id) ? sel.filter((id) => id !== seat.seat_id) : [...sel, seat.seat_id]));
  };
  const rows = [];
  for (let i = 0; i < seats.length; i += 4) rows.push(seats.slice(i, i + 4));

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <BackBar t={t} onBack={() => go("coach")} label="Back to coach selection" />
      <JourneySummary t={t} trainName={ctx.trainName} fromCity={ctx.search.fromCity} toCity={ctx.search.toCity} date={ctx.date} klass={ctx.klass} coachNumber={ctx.coach.coach_number} fare={ctx.fare} />
      <h2 className={`mt-6 mb-3 font-semibold ${t.text}`}>Select Seat(s) — Coach {ctx.coach.coach_number}</h2>
      <div className="flex gap-4 text-xs mb-4">
        <span className={`flex items-center gap-1.5 ${t.subtext}`}><span className="w-3 h-3 rounded-sm bg-neutral-300 inline-block" /> Available</span>
        <span className={`flex items-center gap-1.5 ${t.subtext}`}><span className="w-3 h-3 rounded-sm bg-emerald-600 inline-block" /> Selected</span>
        <span className={`flex items-center gap-1.5 ${t.subtext}`}><span className="w-3 h-3 rounded-sm bg-orange-400 inline-block" /> Held / Sold</span>
      </div>
      <div className={`rounded-xl border p-4 space-y-2 ${t.cardBg}`}>
        {rows.map((row, i) => (
          <div key={i} className="flex gap-2 justify-center">
            {row.map((seat, idx) => {
              const isSel = selected.includes(seat.seat_id);
              const cls = seat.taken ? "bg-orange-400 text-white cursor-not-allowed opacity-70"
                : isSel ? "bg-emerald-600 text-white"
                : `${t.cardAltBg} ${t.text} hover:border-emerald-600`;
              return (
                <React.Fragment key={seat.seat_id}>
                  <button disabled={seat.taken} onClick={() => toggle(seat)} className={`w-11 h-11 rounded-md border text-xs font-semibold flex items-center justify-center ${cls}`}>{seat.seat_number}</button>
                  {idx === 1 && <div className="w-4" />}
                </React.Fragment>
              );
            })}
          </div>
        ))}
      </div>
      <div className="flex items-center justify-between mt-5">
        <p className={`text-sm ${t.subtext}`}>{selected.length} seat(s) selected</p>
        <PrimaryButton t={t} disabled={selected.length === 0} onClick={() => go("passenger", { seats: seats.filter((s) => selected.includes(s.seat_id)) })}>Continue</PrimaryButton>
      </div>
    </div>
  );
}

function PassengerPage({ t, go, ctx, currentUser }) {
  const [passengers, setPassengers] = useState(ctx.seats.map(() => ({ name: "", age: "" })));
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const update = (i, key, val) => setPassengers((p) => p.map((row, idx) => (idx === i ? { ...row, [key]: val } : row)));

  const submit = async () => {
    if (passengers.some((p) => !p.name.trim() || !p.age || Number(p.age) <= 0)) {
      setError("Please enter a valid name and age for every passenger.");
      return;
    }
    setError("");
    setLoading(true);
    try {
      const body = {
        trip_id: ctx.tripId,
        coach_id: ctx.coach.coach_id,
        from: ctx.search.from,
        to: ctx.search.to,
        seats: ctx.seats.map((s, i) => ({ seat_id: s.seat_id, passenger_name: passengers[i].name.trim(), passenger_age: Number(passengers[i].age) })),
      };
      const result = await api("/bookings", { method: "POST", body });
      sessionStorage.setItem(PENDING_BOOKING_KEY, result.booking.pnr_number);
      go("payment", { booking: result });
    } catch (e) {
      if (e.status === 409) { alert(e.message); go("seats"); return; }
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto px-4 py-8">
      <BackBar t={t} onBack={() => go("seats")} label="Back to seat selection" />
      <JourneySummary t={t} trainName={ctx.trainName} fromCity={ctx.search.fromCity} toCity={ctx.search.toCity} date={ctx.date} klass={ctx.klass} coachNumber={ctx.coach.coach_number} fare={ctx.fare} />
      <h2 className={`mt-6 mb-3 font-semibold ${t.text}`}>Passenger Information</h2>
      <div className="space-y-4">
        {ctx.seats.map((seat, i) => (
          <div key={seat.seat_id} className={`rounded-xl border p-4 ${t.cardBg}`}>
            <p className={`text-xs mb-3 ${t.subtext}`}>Seat {seat.seat_number} ({seat.seat_type})</p>
            <div className="grid grid-cols-1 md:grid-cols-[2fr_1fr] gap-3">
              <Field label="Passenger Name" t={t}><input value={passengers[i].name} onChange={(e) => update(i, "name", e.target.value)} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
              <Field label="Age" t={t}><input type="number" min="0" value={passengers[i].age} onChange={(e) => update(i, "age", e.target.value)} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
            </div>
          </div>
        ))}
      </div>
      <ErrorBanner message={error} />
      <div className="flex justify-end mt-5">
        <PrimaryButton t={t} onClick={submit} disabled={loading}>{loading ? "Reserving seat…" : "Continue to Payment"}</PrimaryButton>
      </div>
    </div>
  );
}

function PaymentPage({ t, go, ctx, stations }) {
  const [now, setNow] = useState(Date.now());
  const [method, setMethod] = useState("bKash");
  const [failNext, setFailNext] = useState(false);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [cancelling, setCancelling] = useState(false);

  const booking = ctx.booking.booking;
  const tickets = ctx.booking.tickets;
  const first = tickets[0];
  const bookingDate = new Date(booking.booking_date).getTime();
  const cityOf = (code) => stations.find((s) => s.station_code === code)?.city || code;
  const fromCity = cityOf(booking.starts_at_station);
  const toCity = cityOf(booking.ends_at_station);

  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(id);
  }, []);

  const remaining = HOLD_MS - (now - bookingDate);
  const active = booking.booking_status === "pending" && remaining > 0;

  useEffect(() => {
    if (!active) sessionStorage.removeItem(PENDING_BOOKING_KEY);
  }, [active]);

  if (!active) {
    return (
      <div className="max-w-md mx-auto px-4 py-16 text-center">
        <h1 className={`text-xl font-bold ${t.text}`}>Your temporary seat reservation has expired.</h1>
        <div className="flex gap-3 justify-center mt-6">
          <OutlineButton t={t} onClick={() => go("results")}>Search Again</OutlineButton>
          <PrimaryButton t={t} onClick={() => go("home")}>Return Home</PrimaryButton>
        </div>
      </div>
    );
  }

  const pay = async () => {
    if (failNext) { setError("Payment could not be completed. Please try again."); return; }
    setError("");
    setLoading(true);
    try {
      const result = await api(`/bookings/${booking.pnr_number}/pay`, { method: "POST", body: { method } });
      sessionStorage.removeItem(PENDING_BOOKING_KEY);
      go("ticket", { booking: result });
    } catch (e) {
      // A 410 here means the clock ran out right as payment was submitted;
      // the countdown above will flip to the "expired" view on its own,
      // this message just explains what happened in the meantime.
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const abandonHold = async () => {
    if (ctx.fromMyBookings) { go("mybookings"); return; }
    setCancelling(true);
    setError("");
    try {
      await api(`/bookings/${booking.pnr_number}`, { method: "DELETE" });
      sessionStorage.removeItem(PENDING_BOOKING_KEY);
      go("passenger");
    } catch (e) {
      setError(e.message);
    } finally {
      setCancelling(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto px-4 py-8">
      <BackBar t={t} disabled={cancelling} onBack={abandonHold} label={ctx.fromMyBookings ? "Back to My Bookings" : cancelling ? "Releasing reservation…" : "Back and release reservation"} />
      <JourneySummary t={t} trainName={first.train_name} fromCity={fromCity} toCity={toCity} date={first.departure_date} klass={first.coach_type} coachNumber={first.coach_number} />

      <div className={`mt-4 rounded-md px-4 py-2.5 flex items-center justify-between text-sm ${t.cardAltBg}`}>
        <span className="flex items-center gap-1.5 font-medium text-orange-500">&#9201; Seat held for</span>
        <span className="font-mono font-semibold text-orange-500">{fmtMMSS(remaining)}</span>
      </div>

      <div className={`mt-4 rounded-xl border p-5 ${t.cardBg}`}>
        <h3 className={`font-semibold mb-3 ${t.text}`}>Booking Summary</h3>
        <div className="text-sm space-y-1.5">
          {tickets.map((tk) => (
            <div key={tk.ticket_id} className="flex justify-between">
              <span className={t.subtext}>Passenger — Seat {tk.seat_number}</span>
              <span className={t.text}>{tk.passenger_name}, {tk.passenger_age}y</span>
            </div>
          ))}
        </div>
        <div className={`flex justify-between mt-3 pt-3 border-t font-semibold ${t.divider} ${t.text}`}>
          <span>Total</span><span>৳{booking.fare}</span>
        </div>
      </div>

      <div className={`mt-4 rounded-xl border p-5 ${t.cardBg}`}>
        <h3 className={`font-semibold mb-3 ${t.text}`}>Payment Method</h3>
        <div className="flex gap-3 flex-wrap">
          {["bKash", "Nagad", "Card"].map((m) => (
            <button key={m} onClick={() => setMethod(m)} className={`px-4 py-2 rounded-md border text-sm font-medium ${method === m ? "border-emerald-600 text-emerald-600" : `${t.cardAltBg} ${t.text}`}`}>{m}</button>
          ))}
        </div>
        <label className={`flex items-center gap-2 mt-4 text-xs ${t.subtext}`}>
          <input type="checkbox" checked={failNext} onChange={(e) => setFailNext(e.target.checked)} />
          Simulate a failed payment (for testing)
        </label>
        <ErrorBanner message={error} />
        <PrimaryButton t={t} onClick={pay} disabled={loading || cancelling} className="w-full mt-4">{loading ? "Processing…" : `Pay ৳${booking.fare}`}</PrimaryButton>
      </div>
    </div>
  );
}

function TicketPage({ t, go, ctx, stations }) {
  const { booking, tickets, payment } = ctx.booking;
  const first = tickets[0];
  const cityOf = (code) => stations.find((s) => s.station_code === code)?.city || code;
  const fromCity = cityOf(booking.starts_at_station);
  const toCity = cityOf(booking.ends_at_station);
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=140x140&data=${encodeURIComponent(booking.pnr_number)}`;

  return (
    <div className="max-w-2xl mx-auto px-4 py-8">
      <div className="text-center mb-6">
        <p className="text-3xl">&#9989;</p>
        <h1 className={`text-2xl font-bold ${t.text}`}>Booking Confirmed</h1>
      </div>
      <div className={`rounded-xl border p-6 ${t.cardBg}`}>
        <div className="flex justify-between items-start mb-4">
          <div>
            <p className={`text-xs ${t.subtext}`}>PNR Number</p>
            <p className={`text-lg font-bold tracking-wide ${t.text}`}>{booking.pnr_number}</p>
          </div>
          <img src={qrUrl} alt="Ticket QR code" className="w-20 h-20 rounded" />
        </div>
        <div className={`grid grid-cols-2 gap-y-3 gap-x-4 text-sm border-t pt-4 ${t.divider}`}>
          <InfoRow t={t} label="Train" value={first.train_name} />
          <InfoRow t={t} label="Route" value={`${fromCity} → ${toCity}`} />
          <InfoRow t={t} label="Journey Date" value={fmtDate(first.departure_date)} />
          <InfoRow t={t} label="Class" value={first.coach_type} />
          <InfoRow t={t} label="Coach" value={first.coach_number} />
          <InfoRow t={t} label="Seats" value={tickets.map((tk) => tk.seat_number).join(", ")} />
          <InfoRow t={t} label="Fare" value={`৳${booking.fare}`} />
          <InfoRow t={t} label="Payment" value={payment?.payment_method || "-"} />
        </div>
        <div className={`mt-4 pt-4 border-t ${t.divider}`}>
          <p className={`text-xs font-medium mb-2 ${t.subtext}`}>Passengers</p>
          {tickets.map((tk) => (
            <div key={tk.ticket_id} className="flex justify-between text-sm py-1">
              <span className={t.text}>{tk.passenger_name} ({tk.passenger_age}y)</span>
              <span className={t.subtext}>Seat {tk.seat_number}</span>
            </div>
          ))}
        </div>
      </div>
      <div className="flex flex-wrap gap-3 mt-5 justify-center">
        <OutlineButton t={t} onClick={() => window.print()}>Print Ticket</OutlineButton>
        <OutlineButton t={t} onClick={() => window.print()}>Download Ticket</OutlineButton>
        <PrimaryButton t={t} onClick={() => go("mybookings")}>My Bookings</PrimaryButton>
      </div>
    </div>
  );
}

function MyBookingsPage({ t, go }) {
  const [list, setList] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => { api("/bookings").then(setList).catch((e) => setError(e.message)); }, []);

  const openBooking = async (b) => {
    try {
      const full = await api(`/bookings/${b.pnr_number}`);
      go(full.booking.effective_status === "confirmed" ? "ticket" : "payment", { booking: full, fromMyBookings: true });
    } catch (e) {
      alert(e.message);
    }
  };

  if (error) return <div className="max-w-3xl mx-auto px-4 py-8"><ErrorBanner message={error} /></div>;
  if (!list) return <div className="max-w-3xl mx-auto px-4 py-8"><p className={t.subtext}>Loading bookings…</p></div>;

  const upcoming = list.filter((b) => b.effective_status === "confirmed" || b.effective_status === "pending");
  const past = list.filter((b) => b.effective_status === "expired" || b.effective_status === "cancelled");

  const Row = ({ b }) => {
    const tone = b.effective_status === "confirmed" ? "success" : b.effective_status === "pending" ? "warn" : "danger";
    return (
      <button onClick={() => openBooking(b)} className={`w-full text-left rounded-xl border p-4 flex items-center justify-between ${t.cardBg} hover:border-emerald-600`}>
        <div>
          <p className={`font-medium ${t.text}`}>{b.starts_at_station} → {b.ends_at_station}</p>
          <p className={`text-xs ${t.subtext}`}>PNR {b.pnr_number} · ৳{b.fare} · {fmtDate(b.booking_date)}</p>
        </div>
        <Badge t={t} tone={tone}>{b.effective_status[0].toUpperCase() + b.effective_status.slice(1)}</Badge>
      </button>
    );
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <h1 className={`text-xl font-bold mb-6 ${t.text}`}>My Bookings</h1>
      <h2 className={`text-sm font-semibold mb-2 ${t.subtext}`}>Upcoming</h2>
      <div className="space-y-3 mb-8">
        {upcoming.length === 0 && <p className={`text-sm ${t.subtext}`}>No upcoming bookings.</p>}
        {upcoming.map((b) => <Row key={b.pnr_number} b={b} />)}
      </div>
      <h2 className={`text-sm font-semibold mb-2 ${t.subtext}`}>Previous</h2>
      <div className="space-y-3">
        {past.length === 0 && <p className={`text-sm ${t.subtext}`}>No previous bookings.</p>}
        {past.map((b) => <Row key={b.pnr_number} b={b} />)}
      </div>
    </div>
  );
}

function AdminPage({ t, currentUser }) {
  const [summary, setSummary] = useState(null);
  const [users, setUsers] = useState(null);
  const [bookings, setBookings] = useState(null);
  const [tickets, setTickets] = useState(null);
  const [ticketFilter, setTicketFilter] = useState("");
  const [editingTicket, setEditingTicket] = useState(null);
  const [ticketEdit, setTicketEdit] = useState({ passenger_name: "", passenger_age: "" });
  const [error, setError] = useState("");
  const [ticketError, setTicketError] = useState("");
  const [saving, setSaving] = useState("");
  const [newUser, setNewUser] = useState({ first_name: "", last_name: "", email: "", password: "", role: "customer" });

  const load = async () => {
    setError("");
    try {
      const [nextSummary, nextUsers, nextBookings, nextTickets] = await Promise.all([
        api("/admin/summary"), api("/admin/users"), api("/admin/bookings"), api("/admin/tickets"),
      ]);
      setSummary(nextSummary);
      setUsers(nextUsers);
      setBookings(nextBookings);
      setTickets(nextTickets);
    } catch (e) { setError(e.message); }
  };

  const startEditTicket = (tk) => {
    setTicketError("");
    setEditingTicket(tk.ticket_id);
    setTicketEdit({ passenger_name: tk.passenger_name, passenger_age: String(tk.passenger_age) });
  };
  const cancelEditTicket = () => { setEditingTicket(null); setTicketError(""); };
  const saveTicket = async (ticketId) => {
    setSaving(`ticket-${ticketId}`);
    setTicketError("");
    try {
      const age = Number(ticketEdit.passenger_age);
      if (!ticketEdit.passenger_name.trim() || !age || age <= 0) {
        throw new Error("Please provide a valid name and age.");
      }
      await api(`/admin/tickets/${ticketId}`, {
        method: "PATCH",
        body: { passenger_name: ticketEdit.passenger_name.trim(), passenger_age: age },
      });
      setEditingTicket(null);
      await load();
    } catch (e) { setTicketError(e.message); }
    finally { setSaving(""); }
  };

  useEffect(() => { load(); }, []);

  const changeRole = async (user, role) => {
    setSaving(`role-${user.user_id}`);
    setError("");
    try {
      await api(`/admin/users/${user.user_id}/role`, { method: "PATCH", body: { role } });
      await load();
    } catch (e) { setError(e.message); }
    finally { setSaving(""); }
  };

  const cancelBooking = async (pnr) => {
    if (!window.confirm(`Cancel booking ${pnr}? This releases its seats.`)) return;
    setSaving(`booking-${pnr}`);
    setError("");
    try {
      await api(`/admin/bookings/${encodeURIComponent(pnr)}/cancel`, { method: "PATCH" });
      await load();
    } catch (e) { setError(e.message); }
    finally { setSaving(""); }
  };

  const createUser = async (event) => {
    event.preventDefault();
    setSaving("create-user");
    setError("");
    try {
      await api("/admin/users", { method: "POST", body: newUser });
      setNewUser({ first_name: "", last_name: "", email: "", password: "", role: "customer" });
      await load();
    } catch (e) { setError(e.message); }
    finally { setSaving(""); }
  };

  if (error) return <div className="max-w-4xl mx-auto px-4 py-8"><ErrorBanner message={error} /></div>;
  if (!summary || !users || !bookings) return <div className="max-w-4xl mx-auto px-4 py-8"><p className={t.subtext}>Loading admin dashboard…</p></div>;

  const cards = [
    ["Customers", summary.users.customers],
    ["Administrators", summary.users.admins],
    ["Scheduled trips", summary.trips.scheduled],
    ["Confirmed bookings", summary.bookings.confirmed],
    ["Active payment holds", summary.bookings.pending],
  ];
  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <h1 className={`text-2xl font-bold ${t.text}`}>Admin Dashboard</h1>
      <p className={`mt-1 text-sm ${t.subtext}`}>This area is available only to accounts with administrator privileges.</p>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">
        {cards.map(([label, value]) => (
          <div key={label} className={`rounded-xl border p-5 ${t.cardBg}`}>
            <p className={`text-sm ${t.subtext}`}>{label}</p>
            <p className={`text-3xl font-bold mt-2 ${t.text}`}>{value}</p>
          </div>
        ))}
      </div>

      <section className={`mt-8 rounded-xl border overflow-hidden ${t.cardBg}`}>
        <div className="p-5 border-b"><h2 className={`font-semibold ${t.text}`}>Create Account</h2><p className={`text-sm mt-1 ${t.subtext}`}>Provision a customer or administrator account from the protected admin area.</p></div>
        <form onSubmit={createUser} className="p-5 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3 items-end">
          <Field label="First name" t={t}><input required value={newUser.first_name} onChange={(e) => setNewUser((u) => ({ ...u, first_name: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
          <Field label="Last name" t={t}><input required value={newUser.last_name} onChange={(e) => setNewUser((u) => ({ ...u, last_name: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
          <Field label="Email" t={t}><input required type="email" value={newUser.email} onChange={(e) => setNewUser((u) => ({ ...u, email: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
          <Field label="Password" t={t}><input required minLength="8" type="password" value={newUser.password} onChange={(e) => setNewUser((u) => ({ ...u, password: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
          <div className="flex gap-2 items-end">
            <Field label="Role" t={t}><select value={newUser.role} onChange={(e) => setNewUser((u) => ({ ...u, role: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`}><option value="customer">Customer</option><option value="admin">Administrator</option></select></Field>
            <PrimaryButton t={t} type="submit" disabled={saving === "create-user"}>{saving === "create-user" ? "Creating…" : "Create"}</PrimaryButton>
          </div>
        </form>
      </section>

      <section className={`mt-8 rounded-xl border overflow-hidden ${t.cardBg}`}>
        <div className="p-5 border-b"><h2 className={`font-semibold ${t.text}`}>User Access</h2><p className={`text-sm mt-1 ${t.subtext}`}>Grant or revoke administrator access for other users.</p></div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className={t.cardAltBg}><tr><th className="p-3">User</th><th className="p-3">Email</th><th className="p-3">Role</th><th className="p-3">Action</th></tr></thead>
            <tbody>
              {users.map((u) => <tr key={u.user_id} className={`border-t ${t.divider}`}>
                <td className={`p-3 font-medium ${t.text}`}>{u.first_name} {u.last_name}{u.user_id === currentUser.user_id ? " (You)" : ""}</td>
                <td className={`p-3 ${t.subtext}`}>{u.email}</td>
                <td className="p-3"><Badge t={t} tone={u.role === "admin" ? "success" : "default"}>{u.role}</Badge></td>
                <td className="p-3">
                  {u.user_id === currentUser.user_id ? <span className={t.subtext}>Protected</span> : (
                    <button disabled={saving === `role-${u.user_id}`} onClick={() => changeRole(u, u.role === "admin" ? "customer" : "admin")} className="text-emerald-600 hover:underline disabled:opacity-50">
                      {saving === `role-${u.user_id}` ? "Saving…" : u.role === "admin" ? "Make customer" : "Make admin"}
                    </button>
                  )}
                </td>
              </tr>)}
            </tbody>
          </table>
        </div>
      </section>

      <section className={`mt-8 rounded-xl border overflow-hidden ${t.cardBg}`}>
        <div className="p-5 border-b"><h2 className={`font-semibold ${t.text}`}>All Bookings</h2><p className={`text-sm mt-1 ${t.subtext}`}>Cancel pending or confirmed bookings when necessary.</p></div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className={t.cardAltBg}><tr><th className="p-3">PNR / Passenger</th><th className="p-3">Journey</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead>
            <tbody>
              {bookings.length === 0 && <tr><td colSpan="4" className={`p-4 ${t.subtext}`}>No bookings yet.</td></tr>}
              {bookings.map((b) => <tr key={b.pnr_number} className={`border-t ${t.divider}`}>
                <td className="p-3"><p className={`font-medium ${t.text}`}>{b.pnr_number}</p><p className={t.subtext}>{b.first_name} {b.last_name} · {b.passenger_count} passenger(s)</p></td>
                <td className={`p-3 ${t.subtext}`}>{b.starts_at_station} → {b.ends_at_station}<br />{b.train_names || "—"}{b.departure_date ? ` · ${fmtDate(b.departure_date)}` : ""}</td>
                <td className="p-3"><Badge t={t} tone={b.booking_status === "confirmed" ? "success" : b.booking_status === "pending" ? "warn" : "danger"}>{b.booking_status}</Badge></td>
                <td className="p-3">
                  {["pending", "confirmed"].includes(b.booking_status) ? <button disabled={saving === `booking-${b.pnr_number}`} onClick={() => cancelBooking(b.pnr_number)} className="text-red-500 hover:underline disabled:opacity-50">{saving === `booking-${b.pnr_number}` ? "Cancelling…" : "Cancel"}</button> : <span className={t.subtext}>—</span>}
                </td>
              </tr>)}
            </tbody>
          </table>
        </div>
      </section>

      <section className={`mt-8 rounded-xl border overflow-hidden ${t.cardBg}`}>
        <div className="p-5 border-b flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div>
            <h2 className={`font-semibold ${t.text}`}>All Tickets</h2>
            <p className={`text-sm mt-1 ${t.subtext}`}>Every passenger ticket ever issued, across every booking. Correct a misspelled name or wrong age here.</p>
          </div>
          <input value={ticketFilter} onChange={(e) => setTicketFilter(e.target.value)} placeholder="Filter by PNR, name or train…"
            className={`px-3 py-2 rounded-md border text-sm w-full sm:w-64 ${t.inputBg}`} />
        </div>
        <ErrorBanner message={ticketError} />
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className={t.cardAltBg}><tr><th className="p-3">PNR</th><th className="p-3">Passenger</th><th className="p-3">Journey</th><th className="p-3">Seat</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead>
            <tbody>
              {!tickets && <tr><td colSpan="6" className={`p-4 ${t.subtext}`}>Loading tickets…</td></tr>}
              {tickets && tickets.length === 0 && <tr><td colSpan="6" className={`p-4 ${t.subtext}`}>No tickets have been issued yet.</td></tr>}
              {tickets && tickets
                .filter((tk) => {
                  const q = ticketFilter.trim().toLowerCase();
                  if (!q) return true;
                  return [tk.pnr_number, tk.passenger_name, tk.train_name, tk.first_name, tk.last_name]
                    .some((v) => (v || "").toLowerCase().includes(q));
                })
                .map((tk) => {
                  const editing = editingTicket === tk.ticket_id;
                  return (
                    <tr key={tk.ticket_id} className={`border-t ${t.divider}`}>
                      <td className={`p-3 font-medium ${t.text}`}>{tk.pnr_number}</td>
                      <td className="p-3">
                        {editing ? (
                          <div className="flex gap-2">
                            <input value={ticketEdit.passenger_name} onChange={(e) => setTicketEdit((f) => ({ ...f, passenger_name: e.target.value }))}
                              className={`w-32 px-2 py-1.5 rounded-md border text-sm ${t.inputBg}`} placeholder="Name" />
                            <input type="number" min="1" value={ticketEdit.passenger_age} onChange={(e) => setTicketEdit((f) => ({ ...f, passenger_age: e.target.value }))}
                              className={`w-16 px-2 py-1.5 rounded-md border text-sm ${t.inputBg}`} placeholder="Age" />
                          </div>
                        ) : (
                          <>
                            <p className={`font-medium ${t.text}`}>{tk.passenger_name}, {tk.passenger_age}y</p>
                            <p className={t.subtext}>Booked by {tk.first_name} {tk.last_name}</p>
                          </>
                        )}
                      </td>
                      <td className={`p-3 ${t.subtext}`}>{tk.starts_at_station} → {tk.ends_at_station}<br />{tk.train_name}{tk.departure_date ? ` · ${fmtDate(tk.departure_date)}` : ""}</td>
                      <td className={`p-3 ${t.subtext}`}>Coach {tk.coach_number} · {tk.seat_number}<br />{tk.coach_type}</td>
                      <td className="p-3"><Badge t={t} tone={tk.booking_status === "confirmed" ? "success" : tk.booking_status === "pending" ? "warn" : "danger"}>{tk.booking_status}</Badge></td>
                      <td className="p-3">
                        {editing ? (
                          <div className="flex gap-2">
                            <button disabled={saving === `ticket-${tk.ticket_id}`} onClick={() => saveTicket(tk.ticket_id)} className="text-emerald-600 hover:underline disabled:opacity-50">
                              {saving === `ticket-${tk.ticket_id}` ? "Saving…" : "Save"}
                            </button>
                            <button onClick={cancelEditTicket} className={t.subtext}>Cancel</button>
                          </div>
                        ) : (
                          <button onClick={() => startEditTicket(tk)} className="text-emerald-600 hover:underline">Edit</button>
                        )}
                      </td>
                    </tr>
                  );
                })}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

function ClassInfoPage({ t }) {
  const [classes, setClasses] = useState(null);
  useEffect(() => { api("/classes", { auth: false }).then(setClasses).catch(() => setClasses([])); }, []);
  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <h1 className={`text-2xl font-bold mb-6 ${t.text}`}>Class Information</h1>
      <div className="space-y-4">
        {classes === null && <p className={t.subtext}>Loading…</p>}
        {classes && classes.map((c) => (
          <div key={c.coach_type} className={`rounded-xl border p-5 ${t.cardBg}`}>
            <div className="flex items-center justify-between mb-3">
              <h2 className={`font-semibold ${t.text}`}>{c.coach_type}</h2>
              <span className={`text-sm font-semibold ${t.text}`}>৳{c.fare ?? "—"}</span>
            </div>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <InfoRow t={t} label="Seat Type" value={c.seatType} />
              <InfoRow t={t} label="Comfort" value={c.comfort} />
              <InfoRow t={t} label="AC / Non-AC" value={c.ac} />
              <InfoRow t={t} label="Typical Use" value={c.use} />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function AboutPage({ t }) {
  const Section = ({ title, children }) => (
    <div className="mb-6">
      <h2 className={`font-semibold mb-1.5 ${t.text}`}>{title}</h2>
      <p className={`text-sm leading-relaxed ${t.subtext}`}>{children}</p>
    </div>
  );
  return (
    <div className="max-w-2xl mx-auto px-4 py-10">
      <h1 className={`text-2xl font-bold mb-6 ${t.text}`}>About Us</h1>
      <Section title="About Bangladesh Railway">Bangladesh Railway operates the national rail network, connecting major cities and districts across the country with passenger and freight services.</Section>
      <Section title="Our Purpose">This platform lets passengers search train schedules, check seat availability by class, and complete a ticket booking online from start to finish.</Section>
      <Section title="Our Vision">Make rail travel in Bangladesh easier to plan by giving passengers clear, real-time information and a simple booking flow.</Section>
      <Section title="Why use this platform?">Live seat availability by class, a guided seat-to-payment flow, a temporary hold that protects your seat while you pay, and digital tickets available anytime under My Bookings.</Section>
      <div className={`mt-8 rounded-md border p-4 text-sm ${t.cardAltBg} ${t.text}`}>This is a demonstration/prototype platform and is not an official Bangladesh Railway website.</div>
    </div>
  );
}

function ContactPage({ t }) {
  const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" });
  const [sent, setSent] = useState(false);
  const faqs = [
    ["How do I search for a train?", "Enter your origin, destination, journey date and class on the home page, then select Search Trains."],
    ["How do I select a seat?", "After choosing a class and coach, tap any available seat in the seat map to select it."],
    ["How long is a seat held?", "Once you confirm passenger details, your seat is held for 5 minutes while you complete payment."],
    ["What happens if payment fails?", "The seat remains held until the 5-minute window ends; you can retry payment before it expires."],
    ["How can I view my booking?", "Go to My Bookings from the account menu to see upcoming and past journeys."],
  ];
  return (
    <div className="max-w-2xl mx-auto px-4 py-10">
      <h1 className={`text-2xl font-bold mb-6 ${t.text}`}>Contact Us</h1>
      <div className={`rounded-xl border p-5 space-y-3 ${t.cardBg}`}>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Name" t={t}><input value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
          <Field label="Email" t={t}><input value={form.email} onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
        </div>
        <Field label="Subject" t={t}><input value={form.subject} onChange={(e) => setForm((f) => ({ ...f, subject: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
        <Field label="Message" t={t}><textarea rows={4} value={form.message} onChange={(e) => setForm((f) => ({ ...f, message: e.target.value }))} className={`w-full px-3 py-2.5 rounded-md border text-sm ${t.inputBg}`} /></Field>
        {sent && <p className="text-sm text-green-600">Message sent — thank you (demo, not delivered).</p>}
        <PrimaryButton t={t} onClick={() => setSent(true)}>Send Message</PrimaryButton>
      </div>
      <div className={`mt-6 rounded-xl border p-5 grid grid-cols-1 md:grid-cols-2 gap-3 ${t.cardBg}`}>
        <div className={`text-sm ${t.text}`}>&#9993; support@bdrailway-demo.example (placeholder)</div>
        <div className={`text-sm ${t.text}`}>&#9742; 16XXX (placeholder)</div>
      </div>
      <h2 className={`font-semibold mt-8 mb-3 ${t.text}`}>FAQ</h2>
      <div className="space-y-3">
        {faqs.map(([q, a]) => (
          <div key={q} className={`rounded-md border p-3 ${t.cardAltBg}`}>
            <p className={`text-sm font-medium ${t.text}`}>{q}</p>
            <p className={`text-sm mt-1 ${t.subtext}`}>{a}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ============================== Root App ============================== */

function App() {
  const { theme, setTheme, t } = useTheme();
  const [page, setPage] = useState(pageFromLocation);
  const [currentUser, setCurrentUser] = useState(null);
  const [authChecked, setAuthChecked] = useState(false);
  const [pendingSearch, setPendingSearch] = useState(null);
  const [stations, setStations] = useState([]);
  const [classTypes, setClassTypes] = useState([]);
  const [search, setSearch] = useState({ from: "DHK", to: "CTG", date: todayISO(), klass: "" });
  const [searchError, setSearchError] = useState("");
  const [ctx, setCtx] = useState({});

  useEffect(() => {
    api("/stations", { auth: false }).then(setStations).catch(() => setStations([]));
    api("/classes", { auth: false }).then((cs) => setClassTypes(cs.map((c) => c.coach_type))).catch(() => setClassTypes([]));
    api("/auth/me").then((d) => setCurrentUser(d.user)).catch(() => setCurrentUser(null)).finally(() => setAuthChecked(true));
  }, []);

  const go = (p, patch, opts = {}) => {
    setCtx((c) => ({ ...c, ...(patch || {}) }));
    setPage(p);
    // Keep the address bar in sync with in-app navigation so every page the
    // app can show also has a real, bookmarkable/shareable URL.
    const path = ROUTE_PATHS[p] || "/";
    if (window.location.pathname !== path) {
      if (opts.replace) window.history.replaceState({}, "", path);
      else window.history.pushState({}, "", path);
    }
    window.scrollTo(0, 0);
  };

  // Support the browser's Back/Forward buttons.
  useEffect(() => {
    const onPopState = () => setPage(pageFromLocation());
    window.addEventListener("popstate", onPopState);
    return () => window.removeEventListener("popstate", onPopState);
  }, []);

  // Route guard: runs whenever the page or auth state changes, and is the
  // enforcement point for "no admin page without authorization". It redirects
  // (rather than merely hiding content) so a customer typing /admin directly
  // into the address bar — not just clicking a hidden nav link — never lands
  // on the admin dashboard. The admin API itself is independently protected
  // server-side (requireAuth + a fresh DB role check in requireAdmin), so
  // this is defense in depth, not the only guard.
  useEffect(() => {
    if (!authChecked) return;
    if (AUTH_ONLY_PAGES.has(page) && !currentUser) {
      go("login", {}, { replace: true });
      return;
    }
    if (ADMIN_ONLY_PAGES.has(page) && currentUser?.role !== "admin") {
      go("home", {}, { replace: true });
      return;
    }
    if (CONTEXT_ONLY_PAGES.has(page)) {
      const missing =
        (page === "coach" && !ctx.tripId) ||
        (page === "seats" && !ctx.coach) ||
        (page === "passenger" && !ctx.seats) ||
        ((page === "payment" || page === "ticket") && !ctx.booking);
      if (missing) go("home", {}, { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, authChecked, currentUser?.user_id, currentUser?.role]);

  // Restore an in-progress payment after a browser refresh. A PNR in
  // sessionStorage is only a pointer; the API enforces the actual ownership.
  useEffect(() => {
    if (!authChecked || !currentUser) return;
    const pnr = sessionStorage.getItem(PENDING_BOOKING_KEY);
    if (!pnr) return;

    api(`/bookings/${encodeURIComponent(pnr)}`)
      .then((full) => {
        if (full.booking.effective_status !== "pending") {
          sessionStorage.removeItem(PENDING_BOOKING_KEY);
          return;
        }
        go("payment", { booking: full, fromMyBookings: false }, { replace: true });
      })
      .catch(() => sessionStorage.removeItem(PENDING_BOOKING_KEY));
  }, [authChecked, currentUser?.user_id]);

  const validateSearch = () => {
    if (!search.from || !search.to) return "Please choose both a departure and destination station.";
    if (search.from === search.to) return "Departure and destination stations must be different.";
    if (!search.date) return "Please choose a journey date.";
    if (search.date < todayISO()) return "Journey date cannot be in the past.";
    return "";
  };

  const doSearch = () => {
    const err = validateSearch();
    if (err) { setSearchError(err); return; }
    setSearchError("");
    if (!currentUser) { setPendingSearch({ ...search }); go("login"); return; }
    go("results");
  };

  const onLogin = (user) => {
    setCurrentUser(user);
    if (pendingSearch) { setSearch(pendingSearch); setPendingSearch(null); go("results"); }
    else go("home");
  };

  const logout = async () => {
    try { await api("/auth/logout", { method: "POST" }); }
    catch (e) { /* Local state still must not retain an authenticated user. */ }
    setCurrentUser(null);
    go("home");
  };

  // Enrich ctx with station city names + derived fields whenever we move
  // into the coach/seat/passenger/payment flow, so downstream pages don't
  // each have to re-derive them.
  const goBooking = (p, patch) => {
    const enriched = { ...patch };
    if (patch && (patch.tripId !== undefined || page === "results")) {
      enriched.search = {
        from: search.from, to: search.to,
        fromCity: stations.find((s) => s.station_code === search.from)?.city,
        toCity: stations.find((s) => s.station_code === search.to)?.city,
      };
    }
    go(p, enriched);
  };

  let body;
  if (!authChecked) {
    body = <div className="max-w-4xl mx-auto px-4 py-16 text-center text-sm text-neutral-400">Loading…</div>;
  } else if (page === "home") {
    body = <HomePage t={t} search={search} setSearch={setSearch} doSearch={doSearch} searchError={searchError} stations={stations} classTypes={classTypes} />;
  } else if (page === "login") {
    body = <LoginPage t={t} pendingSearch={pendingSearch} onLogin={onLogin} stations={stations} />;
  } else if (page === "results") {
    body = <ResultsPage t={t} search={search} go={goBooking} stations={stations} />;
  } else if (page === "coach" && ctx.tripId) {
    body = <CoachPage t={t} go={goBooking} ctx={ctx} />;
  } else if (page === "seats" && ctx.coach) {
    body = <SeatsPage t={t} go={goBooking} ctx={ctx} />;
  } else if (page === "passenger" && ctx.seats) {
    body = <PassengerPage t={t} go={goBooking} ctx={ctx} currentUser={currentUser} />;
  } else if (page === "payment" && ctx.booking) {
    body = <PaymentPage t={t} go={goBooking} ctx={ctx} stations={stations} />;
  } else if (page === "ticket" && ctx.booking) {
    body = <TicketPage t={t} go={goBooking} ctx={ctx} stations={stations} />;
  } else if (page === "mybookings" && currentUser) {
    body = <MyBookingsPage t={t} go={goBooking} />;
  } else if (page === "admin" && currentUser?.role === "admin") {
    body = <AdminPage t={t} currentUser={currentUser} />;
  } else if (page === "classinfo") {
    body = <ClassInfoPage t={t} />;
  } else if (page === "about") {
    body = <AboutPage t={t} />;
  } else if (page === "contact") {
    body = <ContactPage t={t} />;
  } else if (page === "account" && currentUser) {
    body = (
      <div className="max-w-md mx-auto px-4 py-10">
        <h1 className={`text-2xl font-bold mb-6 ${t.text}`}>Profile</h1>
        <div className={`rounded-xl border p-5 space-y-3 ${t.cardBg}`}>
          <InfoRow t={t} label="First Name" value={currentUser.first_name} />
          <InfoRow t={t} label="Last Name" value={currentUser.last_name} />
          <InfoRow t={t} label="Email" value={currentUser.email} />
          <InfoRow t={t} label="Account Type" value={currentUser.role === "admin" ? "Administrator" : "Customer"} />
        </div>
        <div className="flex gap-3 mt-5">
          <OutlineButton t={t} onClick={() => go("mybookings")}>My Bookings</OutlineButton>
          <PrimaryButton t={t} onClick={logout}>Logout</PrimaryButton>
        </div>
      </div>
    );
  } else {
    // Unknown or not-yet-authorized page: render nothing while the guard
    // effect above redirects, instead of silently falling back to Home.
    body = <div className="max-w-4xl mx-auto px-4 py-16 text-center text-sm text-neutral-400">Loading…</div>;
  }

  return (
    <div className={`min-h-screen ${t.pageBg}`}>
      <NavBar page={page} go={(p) => { if (p === "home") setCtx({}); go(p); }} t={t} setTheme={setTheme} currentUser={currentUser} logout={logout} />
      {body}
      <footer className={`border-t mt-10 py-6 text-center text-xs ${t.divider} ${t.subtext}`}>
        BD Railway — demonstration/prototype platform, not an official Bangladesh Railway website.
      </footer>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
